language: node_js

node_js:
  - 'node'
  - '10'
  - '6'

before_install:
  - npm install
  - npm install -g typescript

script:
  - npm run build

cache:
  directories:
    - "node_modules"